# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Blog of Paul Steele
email: paul_steele@live.com
name: Paul Steele
words_per_minute: 200
description: >- # this means to ignore newlines until "baseurl:"
  Ponderings of a developing human.
defaults: 
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author: Paul Steele
      author_profile: true
      read_time: true
      share: true
      header:
        image: /assets/images/header.jpg
  - scope:
      path: ""
      type: pages
    values:
      author: Paul Steele
      author_profile: true
      header:
        image: /assets/images/header.jpg
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.paul-steele.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: steele_paul
github_username:  paulsteele

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: air
plugins:
  - jekyll-feed

feed:
  categories:
    - tech
    - life
    - planet

include: [_pages]
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Dockerfile
  - k8s.yaml
  - k8s.template.yaml
  - Jenkinsfile
  - .dockerignore
  - .gitignore
