theme: jekyll-text-theme # Gem-based Jekyll Themes
# remote_theme: kitian616/jekyll-TeXt-theme # Jekyll Remote Theme, see https://github.com/benbalter/jekyll-remote-theme for more information.
## => Site Settings
##############################
text_skin: darkblue # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : 'https://blog.paul-steele.com'
baseurl : ''
title   : The Blog of Paul Steele
description: >-
  Ponderings of a developing human.

## => Language and Timezone
##############################
lang: 'en'
timezone: 'America/Indiana/Indianapolis'

## => Author and Social
##############################
author:
  name      : Paul Steele
  avatar    : 'assets/images/bio.jpg'
  bio       : Ponderings of a developing human
  email     : paul@paul-steele.com
  linkedin  : paultsteele
  github    : paulsteele

## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)

## => Markdown Enhancements
##############################
## Mathjax
mathjax: true
mathjax_autoNumber: true
## Mermaid
mermaid: true
## Chart
chart: true

## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need

## => Sources
##############################
sources: unpkg # bootcdn (default), unpkg

## => Sharing
##############################
sharing:
  provider: false # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx


## => Search
##############################
search:
  provider: false # "default" (default), false, "google", "custom"
## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: false
      aside:
        toc: true
      show_edit_on_github: false
      show_subscribe: true
      pageview: false
      show_author_profile: true

feed:
  categories:
    - tech
    - life
    - planet

## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji