baseURL = "https://blog.paul-steele.com"
theme = "hugo-theme-monochrome"
title = "The Blog of Paul Steele"
author = "Paul Steele"
copyright = "© 2022 Paul Steele"
paginate = 5
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true

[[menu.navbar]]
identifier = "categories"
name = "categories"
url = "#"
weight = 10
[[menu.navbar]]
identifier = "category_tech"
name = "Tech"
url = "/categories/tech"
parent = "categories"
weight = 11
[[menu.navbar]]
identifier = "category_devlog"
name = "Dev Log"
url = "/categories/devlog"
parent = "categories"
weight = 12
[[menu.navbar]]
identifier = "category_houraday"
name = "Hour a Day: AI"
url = "/categories/hour-a-day-ai"
parent = "categories"
weight = 13
[[menu.navbar]]
identifier = "category_life"
name = "Life"
url = "/categories/life"
parent = "categories"
weight = 14
[[menu.navbar]]
identifier = "about"
name = "about"
title = "about"
url = "/about/"
weight = 22
[[menu.navbar]]
identifier = "feed"
name = "feed"
title = "feed"
url = "/index.xml"
weight = 22

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
enable_site_search = true # default: false

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/paulsteele"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:paul@paul-steele.com"

[taxonomies]
category = "categories"
tag = "tags"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[privacy]

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services]

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
