apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog
  namespace: deployments
spec:
  ingressClassName: "cloudflare-tunnel"
  rules:
    - host: blog.paul-steele.com
      http:
        paths:
          - backend:
              service:
                name: blog
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - blog.paul-steele.com
---
apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: deployments
spec:
  selector:
    app: blog
  ports:
    - name: blog
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: deployments
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: registry.paul-steele.com/blog:$BUILD_TAG
          ports:
            - name: blog
              containerPort: 80
          imagePullPolicy: Always
      imagePullSecrets:
        - name: registry.paul-steele.com
